### ISSUE TITLE
why is asizeof 1000 times slower than hash function?

### ISSUE THREAD

**Issue by denfromufa** [pympler/pympler#23]
https://groups.google.com/forum/#!topic/sympy/slKi02rzXVE

**Comment by Pankrat** [comment]
The performance difference could be caused by any number of reasons. E.g. it could be as simple as having a very cheap hash method on the object (you don't need to descend to child nodes when computing a hash) or the hash function could be heavily optimized. Without a reproducible example it's hard to tell. 

BTW: Why don't you just measure the size of the serialized object (which I guess you'll have to do anyway when putting something in the cache)?
