### ISSUE TITLE
deprecation warning in pympler/asizeof.py

### ISSUE THREAD

**Issue by wumpus** [pympler/pympler#74]
/home/lindahl/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pympler/asizeof.py:259: DeprecationWarning: unicode_internal codec has been deprecated
  u = u.encode('unicode-internal')  # see .../Lib/test/test_sys.py

https://docs.python.org/3/library/codecs.html says

Deprecated since version 3.3: This representation is obsoleted by PEP 393.

**Comment by mrJean1** [comment]
Thank you.  A fix has been submitted.

**Comment by nbraud** [comment]
FYI, `unicode_internal` has been removed in CPython 3.8, so Pympler is broken in the release candidate.

**Comment by nbraud** [comment]
Looks like this can be closed, since this issue is fixed in `master` (by #88, see [`asizeof.py`](https://github.com/pympler/pympler/pull/88/files#diff-8aa88d81b0d97706eb59aaafad93aeb8L259)), and release 0.7.

@Pankrat FYI, it looks like you forgot to push the release to git (updating the changelog, bumping the version number, ...)

**Comment by Pankrat** [comment]
Thanks @nbraud
